sudo: required
services:
  - docker 

before_install:
  - docker build -t kathpalrk/redux-react-docker-travis -f Dockerfile.dev .
script:
  - docker run kathpalrk/redux-react-docker-travis npm run test -- --coverage 
   

